         
var laptop = [ 
    {id:"1", imgsrc:"laptop1.jpg",title:"HP 15s DU1520TU Intel Celeron N4020 4GB 1TB HDD 15.6 HD Win10 Black (1 Year Warranty)",  description:" HP 15s DU1520TU Intel Celeron N4020 4GB 1TB HDD 15.6 HD Win10 Black (1 Year Warranty" , detail_description:"Description Bluetooth Headphone A-110 Presenting the best Wireless Bluetooth headphone Airbeats A-110.",price:"PKR:45,000" , buy:"BUY NOW" ,stock:"In the Stock",},
  
    {id:"2", imgsrc:"laptop2.jpg",title:"Dell Inspiron 3593 Core i3 10th Gen 4GB 128GB SSD 15.6 FHD Dos Open box (30 days Warranty)", detail_description: "Dell Inspiron 3593 Core i3 10th Gen 4GB 128GB SSD 15.6 FHD Dos Open box (30 days Warranty)", description:"Dell Inspiron 3593 Core i3 10th Gen 4GB 128GB SSD 15.6 FHD Dos Open box (30 days Warranty)" , price:"PKR:60,000", buy:"BUY NOW",stock:"In The Stock",},
  
    {id:"3", imgsrc:"laptop3.jpg",title:"Dell Inspiron 3593 Core i3 10th Gen 4GB 128GB SSD 15.6 FHD Dos Open box (30 days Warranty) ", detail_description:"Dell Inspiron 3593 Core i3 10th Gen 4GB 128GB SSD 15.6 FHD Dos Open box (30 days Warranty)" ,detail_description: "Dell Inspiron 3593 Core i3 10th Gen 4GB 128GB SSD 15.6 FHD Dos Open box (30 days Warranty)",price:"PKR:50,500",buy:"BUY NOW", stock:"In The Stock",},
  
    {id:"4", imgsrc:"laptop4.jpg",title:"Lenovo Ideapad 3 15ITL05 Core i3 11th Gen 4GB 1TB HDD 15.6 FHD Platinum Grey (1 Years Warranty)S", description:"Lenovo Ideapad 3 15ITL05 Core i3 11th Gen 4GB 1TB HDD 15.6 FHD Platinum Grey (1 Years Warranty)S" , detail_description: "Lenovo Ideapad 3 15ITL05 Core i3 11th Gen 4GB 1TB HDD 15.6 FHD Platinum Grey (1 Years Warranty)S",price:"PKR:78,900",buy:"BUY NOW",stock:"In The Stock",},
  
    {id:"5", imgsrc:"laptop5.jpg",title:"Acer Aspire 5 A515-58P-33ZM Core i3 13th Gen 8GB 512GB SSD 15.6″ FHD Win 11 Steel Grey (1 Year Warranty ", description:"Dawlance Refrigerator 9173 Wide Body / M-Chrome Metallic Silver / 12 CFT / 12.12 Limited Edition / Fridge / Freezer" , detail_description: "DESCRIPTION Go invisible with A-105 headphone Do you ever feel like getting lost in the rhythm of the music? If yes, then A-105 is here to give you the best...",price:"PKR:72,200",buy:"BUY NOW", stock:"In The Stock",},
  
    {id:"6", imgsrc:"laptop6.jpg",title:"Lenovo Ideapad 3 15ITL05 Core i3 11th Gen 4GB 1TB HDD 15.6 FHD Platinum Grey (1 Years Warranty)S", description:"Dawlance Refrigerator 9173 Wide Body / M-Chrome Metallic Silver / 12 CFT / 12.12 Limited Edition / Fridge / Freezer" , detail_description: "Description   Whether you want to enjoy TV or enjoy music on-the-go, Blue Beats B-25 wireless TV headphones are a must-have. Top-quality Bluetooth with the ability to allow users to enjoy...",price:"PKR:93,400",buy:"BUY NOW",stock:"In The Stock",},
  
    {id:"7", imgsrc:"lapttp7.jpg",title:"Acer Aspire 5 A515-58P-33ZM Core i3 13th Gen 8GB 512GB SSD 15.6″ FHD Win 11 Steel Grey (1 Year Warranty)", description:"Dawlance Refrigerator 9173 Wide Body / M-Chrome Metallic Silver / 12 CFT / 12.12 Limited Edition / Fridge / Freezer", detail_description: "WDESCRIPTION    Folding HeadphonesAudionic B-999 Blue Beats Wireless folding Headphone provides big sound in a sleek, portable package. It delivers sound that is incredibly clear and revealing, allowing a wonderful",price:"PKR:87.000" , buy:"BUY NOW",stock:"In The Stock",},
  
    {id:"8", imgsrc:"laptop8.jpg",title:"Dell Inspiron 3593 Core i3 10th Gen 4GB 128GB SSD 15.6 FHD Dos Open box (30 days Warranty) ", description:"Dawlance Refrigerator 9173 Wide Body / M-Chrome Metallic Silver / 12 CFT / 12.12 Limited Edition / Fridge / Freezer ", detail_description: "DESCRIPTION    Quality Headset Audionic BlueBeats B-888 is a quality headset that allows users to tune the music to their level and share the music beats through their phone’s sharing.",price:"PKR:3,600" , buy:"BUY NOW",stock:"In The Stock",},
  
    {id:"9", imgsrc:"laptop9.jpg",title:"Dell Inspiron 3593 Core i3 10th Gen 4GB 128GB SSD 15.6 FHD Dos Open box (30 days Warranty) ", description:"Dawlance Refrigerator 9173 Wide Body / M-Chrome Metallic Silver / 12 CFT / 12.12 Limited Edition / Fridge / Freezer", detail_description: "DESCRIPTION  Audionic B-999 Blue Beats Wireless folding Headphone provide big sound in a sleek, portable package. It delivers sound that is incredibly clear and revealing, allowing a wonderful insight into...",price:"PKR:93,900" , buy:"BUY NOW",stock:"In The Stock",},
  
    {id:"10", imgsrc:"laptop10.jpg",title:"Acer Aspire 5 A515-58P-33ZM Core i3 13th Gen 8GB 512GB SSD 15.6″ FHD Win 11 Steel Grey (1 Year Warranty) ", description:"Dawlance Refrigerator 9173 Wide Body / M-Chrome Metallic Silver / 12 CFT / 12.12 Limited Edition / Fridge / Freezer", detail_description: "R-9 Crystal Clear Sound Type-C Handsfree: Whether You Are Commuting, Traveling Or Heading To Gym, R-9 Type C Handsfree Is Your Perfect Partner.",price:"PKR:40,000" , buy:"BUY NOW",stock:"In The Stock",},
  
    {id:"11", imgsrc:"laptop11.jpg",title:"Core i-5 6th generation  confriguatuion 8GB Ram + SSD. ",description:"Dawlance Refrigerator 9173 Wide Body / M-Chrome Metallic Silver / 12 CFT / 12.12 Limited Edition / Fridge / Freezer", detail_description: "Ronin R-14 Handsfree Provides Great Sound Quality. You Can Enjoy Your Music Anywhere, Anytime! It's Both Lightweight And Durable, So You Can Keep It With You At All Times.",price:"PKR:85,500" , buy:"BUY NOW",stock:"In The Stock",},
  
    {id:"12", imgsrc:"laptop12.jpg",title:"Dell Inspiron 3593 Core i3 10th Gen 4GB 128GB SSD 15.6 FHD Dos Open box (30 days Warranty)  ", description:"Dawlance Refrigerator 9173 Wide Body / M-Chrome Metallic Silver / 12 CFT / 12.12 Limited Edition / Fridge / Freezer ", detail_description: "Ronin R-27 Magical Sound Handsfree: Enjoy Your Favorite Tracks With Ronin R-27 Magical Sound Handsfree",price:"PKR:98,000" , buy:"BUY NOW",stock:"In The Stock",},
  
    {id:"13", imgsrc:"laptop13.jpg",title:" Core i-5 6th generation  confriguatuion 8GB Ram + SSD.", description:"Dawlance Refrigerator 9173 Wide Body / M-Chrome Metallic Silver / 12 CFT / 12.12 Limited Edition / Fridge / Freezer", detail_description: "R-15 Genuine Bass Handsfree: Built With A Bio-Cellulose Diaphragm To Produce High-Detail Treble With Superior Bass.",price:"PKR:60,000" , buy:"BUY NOW",stock:"In The Stock",}
    
  ]
  // led tv
  var tv_led= [
    {id:"14", imgsrc:"tv2.jpg",title:"Ecostar 32 Inch Sound Pro Frameless HD LED TV CX-32U576 A+", description:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequatur ab " , detail_description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequatur ab nemo, iusto fugiat ipsam deleniti sunt cumque incidunt iste a.Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequatur ab nemo, iusto fugiat ipsam deleniti sunt cumque incidunt iste a.",price:"85,000", buy:"BUY NOW",stock:"In The Stock",},

    {id:"15", imgsrc:"tv1.jpg",title:"Ecostar 32 Inch Sound Pro Frameless HD LED TV CX-32U576 A+", description:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequatur ab nemo," , detail_description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequatur ab nemo, iusto fugiat ipsam deleniti sunt cumque incidunt iste a.Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequatur ab nemo, iusto fugiat ipsam deleniti sunt cumque incidunt iste a.",price:"PKR:81,000",buy:"BUY NOW",stock:"In The Stock",},

    {id:"16", imgsrc:"tv3.jpg",title:"TCL Smart Led Tv 43″ 43S5200", description:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequatur ab nemo," , detail_description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequatur ab nemo, iusto fugiat ipsam deleniti sunt cumque incidunt iste a.Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequatur ab nemo, iusto fugiat ipsam deleniti sunt cumque incidunt iste a.",price:"PKR:72,000",buy:"BUY NOW",stock:"In The Stock",},

    {id:"17", imgsrc:"tv4.jpg",title:"TCL 55″ 4K UHD Smart LED TV L55P615", description:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequatur ab nemo," , detail_description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequatur ab nemo, iusto fugiat ipsam deleniti sunt cumque incidunt iste a.Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequatur ab nemo, iusto fugiat ipsam deleniti sunt cumque incidunt iste a.",price:"PKR:60,000",buy:"BUY NOW",stock:"In The Stock",},

    {id:"18", imgsrc:"tv5.jpg",title:"TCL 32 Inches Smart HD LED TV 32S65A", description:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequatur ab nemo," , detail_description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequatur ab nemo, iusto fugiat ipsam deleniti sunt cumque incidunt iste a.Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequatur ab nemo, iusto fugiat ipsam deleniti sunt cumque incidunt iste a.",price:"PKR:51,000",buy:"BUY NOW",stock:"In The Stock",},
    
    {id:"19", imgsrc:"tv6.jpg",title:"Samsung 65 Inches LED TV 65AU7000", description:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequatur ab nemo," , detail_description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequatur ab nemo, iusto fugiat ipsam deleniti sunt cumque incidunt iste a.Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequatur ab nemo, iusto fugiat ipsam deleniti sunt cumque incidunt iste a.",price:"PKR:57,000",buy:"BUY NOW",stock:"In The Stock",},

    {id:"20", imgsrc:"tv7.jpg",title:"TCL 4K SUHD Android QLED TV 65C716", description:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequatur ab nemo," , detail_description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequatur ab nemo, iusto fugiat ipsam deleniti sunt cumque incidunt iste a.Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequatur ab nemo, iusto fugiat ipsam deleniti sunt cumque incidunt iste a.",price:"PKR:49,000",buy:"BUY NOW",stock:"In The Stock",},

    {id:"21", imgsrc:"tv8.jpg",title:"TCL 40 Inches Full HD LED TV 40D3000", description:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequatur ab nemo," , detail_description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequatur ab nemo, iusto fugiat ipsam deleniti sunt cumque incidunt iste a.Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequatur ab nemo, iusto fugiat ipsam deleniti sunt cumque incidunt iste a.",price:"PKR:91,000",buy:"BUY NOW",stock:"In The Stock",},

    {id:"22", imgsrc:"tv9.jpg",title:"Ecostar 32 Inch Sound Pro Frameless HD LED TV CX-32U576 A+", description:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequatur ab nemo," , detail_description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequatur ab nemo, iusto fugiat ipsam deleniti sunt cumque incidunt iste a.Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequatur ab nemo, iusto fugiat ipsam deleniti sunt cumque incidunt iste a.",price:"PKR:31,000",buy:"BUY NOW",stock:"In The Stock",},

    {id:"23", imgsrc:"tv10.jpg",title:"Sony 40 Inches Smart Edge Led TV KDL-40W660E", description:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequatur ab nemo," , detail_description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequatur ab nemo, iusto fugiat ipsam deleniti sunt cumque incidunt iste a.Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequatur ab nemo, iusto fugiat ipsam deleniti sunt cumque incidunt iste a.",price:"PKR:67,000",buy:"BUY NOW",stock:"In The Stock",},

    {id:"24", imgsrc:"tv11.jpg",title:"Sony 55 Inches Smart LED TV 55X7000F", description:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequatur ab nemo," , detail_description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequatur ab nemo, iusto fugiat ipsam deleniti sunt cumque incidunt iste a.Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequatur ab nemo, iusto fugiat ipsam deleniti sunt cumque incidunt iste a.",price:"PKR:35,000",buy:"BUY NOW",stock:"In The Stock",},

      ]   

      var smartwatch= [
        {id:"26", imgsrc:"watch.jpg",title:"I7 Pro Max Smart Watch | Android & IOS | Blood Pressure Sensor | Heart Rate Sensor | IP67 Waterproof | Smart Watch", description:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequatur ab " , detail_description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequatur ab nemo, iusto fugiat ipsam deleniti sunt cumque incidunt iste a.Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequatur ab nemo, iusto fugiat ipsam deleniti sunt cumque incidunt iste a.",price:"85000",buy:"BUY NOW",stock:"In The Stock",},
      
        {id:"26", imgsrc:"watch2.jpg",title:"Xiaomi | Mibro Air Smart Watch | Silicone Strap | Heart Rate Monitor | 12 Sports Mode | IP68 Waterproof | SmartWatch", description:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequatur ab nemo," , detail_description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequatur ab nemo, iusto fugiat ipsam deleniti sunt cumque incidunt iste a.Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequatur ab nemo, iusto fugiat ipsam deleniti sunt cumque incidunt iste a.",price:"85000",buy:"BUY NOW",stock:"In The Stock",},
      
        {id:"27", imgsrc:"watch3.jpg",title:"MC72 Pro Smartwatch | 44mm | Bluetooth Call | Body Temperature | ECG Blood Pressure | Heart Rate Monitor | Android IOS | Smart Watch", description:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequatur ab nemo," , detail_description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequatur ab nemo, iusto fugiat ipsam deleniti sunt cumque incidunt iste a.Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequatur ab nemo, iusto fugiat ipsam deleniti sunt cumque incidunt iste a.",price:"85000",buy:"BUY NOW",stock:"In The Stock",},
      
        {id:"28", imgsrc:"watch4.jpg",title:"HW21 Smartwatch | 42mm | IP68 Waterproof | Heart Rate Monitor | Fitness Band | Colorful Touch Screen | Smart Watch", description:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequatur ab nemo," , detail_description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequatur ab nemo, iusto fugiat ipsam deleniti sunt cumque incidunt iste a.Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequatur ab nemo, iusto fugiat ipsam deleniti sunt cumque incidunt iste a.",price:"85000",buy:"BUY NOW",stock:"In The Stock",},
      
        {id:"29", imgsrc:"watch5.jpg",title:" IWO | FK99 Smartwatch | Series 6 | Heart Rate Sensor | Pedometer | Bluetooth music | Push notifications | Smart Watch    ", description:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequatur ab nemo," , detail_description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequatur ab nemo, iusto fugiat ipsam deleniti sunt cumque incidunt iste a.Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequatur ab nemo, iusto fugiat ipsam deleniti sunt cumque incidunt iste a.",price:"85000",buy:"BUY NOW",stock:"In The Stock",},
        
        {id:"30", imgsrc:"watch6.jpg",title:"Xiaomi Mibro A1 | 1.28″ HD Display | 20 Sports Mode | Blood Oxygen Monitor | Heart Rate Sensor | Smart Watch", description:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequatur ab nemo," , detail_description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequatur ab nemo, iusto fugiat ipsam deleniti sunt cumque incidunt iste a.Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequatur ab nemo, iusto fugiat ipsam deleniti sunt cumque incidunt iste a.",price:"85000",buy:"BUY NOW",stock:"In The Stock",},
      
        {id:"31", imgsrc:"watch7.jpg",title:"Haylou GST | Silicone Strap | 22mm | Heart Rate Monitor | Blood Oxygen Monitor | Sleep Monitoring |", description:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequatur ab nemo," , detail_description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequatur ab nemo, iusto fugiat ipsam deleniti sunt cumque incidunt iste a.Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequatur ab nemo, iusto fugiat ipsam deleniti sunt cumque incidunt iste a.",price:"85000",buy:"BUY NOW",stock:"In The Stock",},
      
        {id:"32", imgsrc:"watch8.jpg",title:"HX68 Smartwatch | Bluetooth Call | Android & IOS | Heart Rate Sensor | G Sensor | Sleep Monitor | Smart Watch", description:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequatur ab nemo," , detail_description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequatur ab nemo, iusto fugiat ipsam deleniti sunt cumque incidunt iste a.Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequatur ab nemo, iusto fugiat ipsam deleniti sunt cumque incidunt iste a.",price:"85000",buy:"BUY NOW",stock:"In The Stock",},
      
        {id:"33", imgsrc:"watch9.jpg",title:"HX68 Smartwatch | Bluetooth Call | Android & IOS | Heart Rate Sensor | G Sensor | Sleep Monitor", description:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequatur ab nemo," , detail_description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequatur ab nemo, iusto fugiat ipsam deleniti sunt cumque incidunt iste a.Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequatur ab nemo, iusto fugiat ipsam deleniti sunt cumque incidunt iste a.",price:"85000",buy:"BUY NOW",stock:"In The Stock",},
      
        {id:"34", imgsrc:"watch10.jpg",title:"Haylou Smart Watch 2 | Silicone Strap | 44mm | Heart Rate Monitor | Blood Oxygen Monitor | IP68 Waterproof | Smart Watch", description:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequatur ab nemo," , detail_description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequatur ab nemo, iusto fugiat ipsam deleniti sunt cumque incidunt iste a.Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequatur ab nemo, iusto fugiat ipsam deleniti sunt cumque incidunt iste a.",price:"85000",buy:"BUY NOW",stock:"In The Stock",},
      
        {id:"35", imgsrc:"watch11.jpg",title:"Xiaomi | Mibro Air Smart Watch | Silicone Strap | Heart Rate Monitor | 12 Sports Mode | IP68 Waterproof | SmartWatch", description:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequatur ab nemo," , detail_description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequatur ab nemo, iusto fugiat ipsam deleniti sunt cumque incidunt iste a.Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequatur ab nemo, iusto fugiat ipsam deleniti sunt cumque incidunt iste a.",price:"85000",buy:"BUY NOW",stock:"In The Stock",}
      
        
      ]   
      
  
  
  